development:
  adapter: postgresql
  encoding: unicode
  database: Cheerz_development
  pool: 5
  username: hugo
  password: root
  host: localhost

test:
  adapter: postgresql
  encoding: unicode
  database: Cheerz_test
  pool: 5
  username: hugo
  password: root

production:
  adapter: postgresql
  encoding: unicode
  database: Cheerz_production
  pool: 5
  username: <%= ENV['POSTGRESQL_USER'] %>
  password: <%= ENV['POSTGRESQL_PASSWORD'] %>